### ISSUE TITLE
Update the screenshots of before/ after

### ISSUE THREAD

**Issue by hupili** [initiumlab/imageholics#8]
@Kateliuxue  you can try this issue. Similar to the previous one to update readme

**Comment by hupili** [comment]
@Kateliuxue  this one may need a Git client to finish. You can consult other group members on Git GUI.

**Comment by Kateliuxue** [comment]
The screenshots have been updated.

**Comment by hupili** [comment]
@Kateliuxue   there is much blank in the screenshot. The pic in the frontpage needs to catch attention by first glance. Let's trim down to the core region. 

Original: 

![](https://raw.githubusercontent.com/initiumlab/imageholics/master/misc/example1-before.jpg)

Better:

<img width="177" alt="screen shot 2015-09-12 at 12 58 55 am" src="https://cloud.githubusercontent.com/assets/1227160/9820895/81b7dd10-58e9-11e5-8911-729eac873f8c.png">

**Comment by hupili** [comment]
The window and the scroll bar is not so important.
